// <auto-generated />
using System;
using Danfoss.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Danfoss.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Danfoss.Models.House", b =>
                {
                    b.Property<int>("HouseID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address");

                    b.Property<int?>("WatermeterID");

                    b.HasKey("HouseID");

                    b.HasIndex("WatermeterID");

                    b.ToTable("Houses");
                });

            modelBuilder.Entity("Danfoss.Models.WaterMeter", b =>
                {
                    b.Property<int>("WatermeterID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("FactoryNumber");

                    b.Property<int>("Indication");

                    b.HasKey("WatermeterID");

                    b.ToTable("WaterMeter");
                });

            modelBuilder.Entity("Danfoss.Models.House", b =>
                {
                    b.HasOne("Danfoss.Models.WaterMeter", "waterMeter")
                        .WithMany()
                        .HasForeignKey("WatermeterID");
                });
#pragma warning restore 612, 618
        }
    }
}
